name: wallpaper_app_flutter
version: 1.0.0+1
description: Anime wallpaper app with online browsing and AI generation.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  flutter_riverpod: ^2.5.1
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  wallpaper_manager_flutter: ^0.0.2

flutter:
  uses-material-design: true
